export const CREATE_EXPENSE_REQUEST = 'CREATE_EXPENSE_REQUEST';
export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS';
export const CREATE_EXPENSE_FAIL = 'CREATE_EXPENSE_FAIL';
export const CREATE_EXPENSE_RESET = 'CREATE_EXPENSE_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const UPDATE_EXPENSE_REQUEST = 'UPDATE_EXPENSE_REQUEST';
export const UPDATE_EXPENSE_SUCCESS = 'UPDATE_EXPENSE_SUCCESS';
export const UPDATE_EXPENSE_FAIL = 'UPDATE_EXPENSE_FAIL';
export const UPDATE_EXPENSE_RESET = 'UPDATE_EXPENSE_RESET';

export const MY_EXPENSE_REQUEST = 'MY_EXPENSE_REQUEST';
export const MY_EXPENSE_SUCCESS = 'MY_EXPENSE_SUCCESS';
export const MY_EXPENSE_FAIL = 'MY_EXPENSE_FAIL';
export const MY_EXPENSE_RESET = 'MY_EXPENSE_RESET';

export const ALL_EXPENSE_REQUEST = 'ALL_EXPENSE_REQUEST';
export const ALL_EXPENSE_SUCCESS = 'ALL_EXPENSE_SUCCESS';
export const ALL_EXPENSE_FAIL = 'ALL_EXPENSE_FAIL';
export const ALL_EXPENSE_RESET = 'ALL_EXPENSE_RESET';

export const GET_EXPENSE_REQUEST = 'GET_EXPENSE_REQUEST';
export const GET_EXPENSE_SUCCESS = 'GET_EXPENSE_SUCCESS';
export const GET_EXPENSE_FAIL = 'GET_EXPENSE_FAIL';
export const GET_EXPENSE_RESET = 'GET_EXPENSE_RESET';

export const DELETE_EXPENSE_REQUEST = 'DELETE_EXPENSE_REQUEST';
export const DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS';
export const DELETE_EXPENSE_FAIL = 'DELETE_EXPENSE_FAIL';
export const DELETE_EXPENSE_RESET = 'DELETE_EXPENSE_RESET';